[package]
name = "kanari"
version = "0.1.0"
edition = "2024"

[dependencies]
bdk_wallet = { version = "2", features = ["rusqlite"] }
bdk_electrum = "0.23"
miniscript = "12.3"
axum = "0.8"
tower-http = { version = "0.6", features = ["cors"] }
tokio = { version = "1.46", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
utoipa = { version = "5.4", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9", features = ["axum"] }
utoipa-axum = "0.2"
anyhow = "1.0"
secp256k1 = "0.31"
chrono = "0.4"
reqwest = { version = "0.12", features = ["json"] }
base64 = "0.22"
clap = { version = "4.0", features = ["derive"] }
dotenvy = "0.15"
phonenumber = "0.3"
axum-streams = "0.6"
tokio-stream = { version = "0.1", features = ["sync"] }
futures-util = "0.3"

[dev-dependencies]
http-body-util = "0.1"
tower = { version = "0.5", features = ["util"] }
mime = "0.3"
tempfile = "3.3"
uuid = { version = "1", features = ["v4"] }